site_name: Geotrek-rando v3
theme:
  name: readthedocs
  logo : img/logo.svg
  include_homepage_in_sidebar: false
  hljs_languages:
    - yaml
    - markdown
nav:
  - Home: index.md
  - ğŸ’¡ Introduction: 
    - Presentation: presentation-fr.md
  - ğŸš€ Customization: 
    - Customization: customization.md
    - Scripts and GDPR: customization-scripts-GDPR.md
    - Icons : icons.md
  - ğŸ”§ Developer Guide: 
    - Installation: installation.md
    - Developement: development.md
  - âœ¨ Knowledge: 
      - Caching: knowledge/caching.md
      - Debug: knowledge/debug.md
      - Pages and navigation: knowledge/pages-and-navigation.md
      - Server side rendering: knowledge/server-side-rendering.md
  - ğŸ“ Changelog: 
    - Changelog: changelog.md
